{% set name = "numba_celltree" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c1babcda3becbfa8fd600a49e3c6de6ac67ea3c3d19ec0fc8e81f563ac67a307

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numba >=0.50
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - numba_celltree

about:
  home: https://github.com/deltares/numba_celltree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    Celltree data structure for searching for points, lines, boxes, and cells
    (convex polygons) in a two dimensional unstructured mesh.
  description: |
    Finding your way around in an unstructured meshes is difficult. Numba Celltree
    provides methods for searching for points, lines, boxes, and cells (convex
    polygons) in a two dimensional unstructured mesh.
  doc_url: https://deltares.github.io/numba_celltree/
  dev_url: https://github.com/deltares/numba_celltree

extra:
  recipe-maintainers:
    - JoerivanEngelen
    - deltares-service-account
    - Huite
